version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: zkp-postgres
    environment:
      POSTGRES_DB: zkp_file_sharing
      POSTGRES_USER: zkp_user
      POSTGRES_PASSWORD: zkp_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - zkp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zkp_user -d zkp_file_sharing"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: zkp-minio
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password123
      MINIO_DOMAIN: localhost
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - zkp-network
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Redis for Caching (optional but useful for rate limiting)
  redis:
    image: redis:7-alpine
    container_name: zkp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - zkp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # MinIO Client for bucket initialization
  minio-init:
    image: minio/mc:latest
    container_name: zkp-minio-init
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - zkp-network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio_admin minio_password123;
      /usr/bin/mc mb myminio/zkp-files --ignore-existing;
      /usr/bin/mc policy set public myminio/zkp-files;
      exit 0;
      "

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  zkp-network:
    driver: bridge 