services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: zkp-postgres
    environment:
      POSTGRES_DB: zkp_file_sharing
      POSTGRES_USER: zkp_user
      POSTGRES_PASSWORD: zkp_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zkp_user -d zkp_file_sharing"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zkp-network

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: zkp-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password123
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - zkp-network

  # Redis for Caching
  redis:
    image: redis:7-alpine
    container_name: zkp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - zkp-network

  # MinIO Client for bucket initialization
  minio-setup:
    image: minio/mc:latest
    container_name: zkp-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set myminio http://minio:9000 minio_admin minio_password123;
      /usr/bin/mc mb myminio/zkp-files --ignore-existing;
      /usr/bin/mc anonymous set none myminio/zkp-files;
      echo 'MinIO bucket setup complete';
      "
    restart: "no"
    networks:
      - zkp-network

  # FastAPI Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zkp-backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://zkp_user:zkp_password@postgres:5432/zkp_file_sharing
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minio_admin
      - MINIO_SECRET_KEY=minio_password123
      - MINIO_BUCKET_NAME=zkp-files
      - MINIO_SECURE=false
      - REDIS_URL=redis://redis:6379/0
      - JWT_SECRET_KEY=super-secret-jwt-key-change-this-in-production-docker
      - JWT_ALGORITHM=HS256
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
      - CORS_ORIGINS=["http://localhost:3000","http://localhost:80","http://frontend:80"]
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zkp-network

  # React Frontend
  frontend:
    build:
      context: ./UI/zkp-frontend
      dockerfile: Dockerfile
    container_name: zkp-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - zkp-network

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  zkp-network:
    driver: bridge
    name: zkp-network 